-- Datos de ejemplo para desarrollo local
INSERT INTO leads (negocio, fecha_mensaje, nombre, telefono, tipo_mensaje, mensaje, categoria, subcategoria, producto, detalle, ciudad, provincia, intencion, urgencia, requiere_humano, resumen, pregunta, forma_pago, precio, cantidad, problema, respuesta_sugerida, etiquetas, estado, notas)
VALUES
('piscinas', now() - interval '2 hours', 'Marcela Gómez', '5493514567890', 'texto', 'Hola! Quería saber el precio de una pileta de fibra de 6x3 y si tienen financiación en cuotas. La querría instalar este mes.', 'precio', 'pileta fibra', 'pileta de fibra', '6x3', 'Córdoba', 'Córdoba', 'alta', 'alta', false, 'Consulta precio + financiación pileta 6x3, quiere instalar este mes', '¿Precio y financiación de pileta 6x3?', 'cuotas', '', '1', '', 'Te paso precio de la 6x3 y planes de financiación en cuotas.', 'precio, financiacion, instalacion', 'nuevo', NULL),
('piscinas', now() - interval '5 hours', 'Diego Fernández', '5491150012345', 'texto', 'Buenas, hacen la instalación en Córdoba capital? Cuánto demora la obra?', 'instalacion', 'tiempos', 'instalación', '', 'Córdoba', 'Córdoba', 'media', 'media', false, 'Consulta instalación en Córdoba capital y demora de obra', '¿Instalan en Córdoba y cuánto demora?', '', '', '', '', 'Sí, instalamos en Córdoba capital. La obra demora X días.', 'instalacion, zona', 'contactado', 'Le pasé info de zonas'),
('piscinas', now() - interval '1 day', 'Sandra Ruiz', '5493624778899', 'texto', 'Compré una bomba hace 2 meses y dejó de funcionar, pierde agua por abajo. Necesito que vengan a verla, está en garantía.', 'reclamo', 'bomba', 'bomba de filtrado', '', '', '', 'baja', 'alta', true, 'Reclamo por bomba con pérdida en garantía, pide visita técnica', '¿Pueden venir a revisar la bomba en garantía?', '', '', '', 'bomba pierde agua', 'Coordinamos visita técnica por garantía.', 'reclamo, garantia', 'nuevo', NULL),
('piscinas', now() - interval '3 hours', 'José Pérez', '5492215566778', 'audio', 'Hola quería saber qué producto me conviene para el agua verde de la pileta', 'quimicos', 'agua verde', 'alguicida', '', 'La Plata', 'Buenos Aires', 'media', 'media', false, 'Consulta químico para agua verde', '¿Qué producto para agua verde?', '', '', '', 'agua verde / algas', 'Te recomiendo alguicida + clarificador.', 'quimicos, mantenimiento', 'nuevo', NULL),
('piscinas', now() - interval '2 days', 'Laura Méndez', '5493815544332', 'texto', 'Cuánto sale el metro de revestimiento atérmico? Tengo 40 m2 para hacer.', 'pisos_atermicos', 'precio', 'piso atérmico', '40 m2', 'San Miguel de Tucumán', 'Tucumán', 'alta', 'media', false, 'Consulta precio piso atérmico para 40 m2', '¿Precio del m2 de piso atérmico?', '', '', '40 m2', '', 'Te paso el precio por m2 del atérmico.', 'pisos_atermicos, precio', 'presupuesto', 'Enviado presupuesto por 40m2'),
('piscinas', now() - interval '6 days', 'Roberto Díaz', '5491166778899', 'texto', 'Gracias, ya compré con ustedes la pileta. Excelente atención!', 'otro', 'agradecimiento', '', '', '', '', 'baja', 'baja', false, 'Cliente agradece la compra', '', '', '', '', '', '', 'otro', 'ganado', 'Venta cerrada'),
('vivero', now() - interval '1 hour', 'Carla Suárez', '5493512233445', 'texto', 'Hola, tenés jazmines en maceta? Necesito unos 10 para una cerca. Cuánto sale cada uno?', 'plantas', 'jazmin', 'jazmín en maceta', 'jazmín', 'Córdoba', 'Córdoba', 'alta', 'media', false, 'Consulta disponibilidad y precio de 10 jazmines en maceta', '¿Tenés jazmines y a qué precio?', '', '', '10', '', 'Sí, tenemos jazmines en maceta. El precio por unidad es X.', 'plantas, precio, cantidad', 'nuevo', NULL),
('vivero', now() - interval '4 hours', 'Pedro Lucero', '5493884455667', 'imagen', 'Mi limonero tiene las hojas con manchas amarillas y unos bichitos blancos. [Imagen]: hojas de cítrico con cochinilla', 'plagas_enfermedades', 'citricos', 'limonero', 'limonero', 'San Salvador de Jujuy', 'Jujuy', 'media', 'alta', true, 'Limonero con cochinilla y manchas, pide tratamiento', '¿Qué le pongo al limonero con plaga?', '', '', '', 'cochinilla en limonero', 'Es cochinilla. Te recomiendo aceite + insecticida específico.', 'plagas_enfermedades, citricos', 'nuevo', NULL),
('vivero', now() - interval '8 hours', 'Anabel Torres', '5491133221100', 'texto', 'Qué plantas me recomendás para un balcón que recibe sol toda la tarde?', 'asesoramiento', 'balcon', 'plantas de sol', '', 'CABA', 'Buenos Aires', 'baja', 'baja', false, 'Asesoramiento plantas para balcón con sol de tarde', '¿Qué plantas para balcón soleado?', '', '', '', '', 'Para sol fuerte: lavanda, romero, suculentas, geranios.', 'asesoramiento, plantas', 'contactado', NULL),
('vivero', now() - interval '1 day', 'Miguel Ávalos', '5493417788990', 'texto', 'Cuánto está el metro de césped en rollo? Hacen entrega a domicilio en Rosario?', 'cesped', 'precio', 'césped en rollo', '', 'Rosario', 'Santa Fe', 'alta', 'alta', false, 'Precio césped en rollo y envío a Rosario', '¿Precio del césped en rollo y envío?', '', '', '', '', 'Te paso precio por m2 y costo de envío a Rosario.', 'cesped, precio, envio', 'nuevo', NULL),
('vivero', now() - interval '3 days', 'Florencia Paz', '5492996655443', 'texto', 'Necesito tierra y sustrato para trasplantar. Tenés bolsas grandes?', 'sustratos_tierra', 'sustrato', 'sustrato y tierra', '', 'Neuquén', 'Neuquén', 'media', 'baja', false, 'Consulta sustrato y tierra en bolsas grandes', '¿Tenés sustrato en bolsa grande?', '', '', '', '', 'Sí, tenemos sustrato y tierra en bolsas de 20 y 50 litros.', 'sustratos_tierra, stock', 'presupuesto', NULL),
('vivero', now() - interval '5 days', 'Hernán Ríos', '5493512277889', 'texto', 'Hola, compré 20 plantines la semana pasada, gracias!', 'otro', 'agradecimiento', 'plantines', '', 'Córdoba', 'Córdoba', 'baja', 'baja', false, 'Cliente agradece compra de plantines', '', '', '', '20', '', '', 'otro', 'ganado', NULL);
